import { BarChart3, Check, Flame, LayoutGrid, Play, Target, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { SectionFrame } from "./SectionFrame";

/** Responsive CSS-only mobile app preview. */
export default function MobilePreview() {
  return <SectionFrame><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="mx-auto w-64 rotate-[-3deg] rounded-[2rem] border-4 border-foreground bg-foreground p-2 shadow-2xl"><div className="relative aspect-[.52] overflow-hidden rounded-[1.5rem] bg-background"><div className="mx-auto mt-1 h-4 w-20 rounded-full bg-foreground" /><div className="space-y-3 p-4 pt-8"><small className="text-muted-foreground">Tuesday, Aug 21</small><h3 className="font-heading text-lg font-semibold">Good morning, Alex</h3><Card className="gap-3 bg-[var(--accent-atomic)] p-3 text-[var(--accent-atomic-foreground)]"><span className="flex items-center gap-1 text-[10px]"><Flame className="size-3" />12 day streak</span><strong className="font-heading">One step at a time.</strong><span className="block h-1 rounded bg-[var(--accent-atomic-foreground)]/20"><span className="block h-full w-3/4 rounded bg-[var(--accent-atomic-foreground)]" /></span></Card>{[[true, "Plan the day", "15 min"], [false, "Deep work block", "45 min"], [false, "Evening reflection", "10 min"]].map(([complete, task, time]) => <div className="flex items-center gap-2 border-b py-2 text-[10px]" key={task}><span className={`grid size-4 place-items-center rounded border ${complete ? "border-[var(--accent-atomic)] bg-[var(--accent-atomic)]" : "border-border"}`}>{complete && <Check className="size-3 text-[var(--accent-atomic-foreground)]" />}</span><strong className="flex-1">{task}</strong><small className="text-muted-foreground">{time}</small></div>)}</div><div className="absolute inset-x-0 bottom-0 flex justify-around bg-card p-3 text-muted-foreground"><LayoutGrid className="size-4 text-[var(--accent-atomic)]" /><Target className="size-4" /><BarChart3 className="size-4" /><Users className="size-4" /></div></div></div><div><span className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Your progress, in your pocket</span><h2 className="mt-3 font-heading text-3xl font-semibold tracking-tight sm:text-4xl">Available on iOS & Android.</h2><p className="mt-4 max-w-lg text-muted-foreground">Capture the next thing wherever the day finds you. AtomicTasks keeps your plan close without asking for your whole attention.</p><div className="mt-6 flex flex-wrap gap-3"><Button className="h-12 bg-foreground text-background hover:bg-foreground/90"><span className="text-xl"></span><span className="grid text-left text-[9px]">Download on the<strong className="text-sm">App Store</strong></span></Button><Button className="h-12 bg-foreground text-background hover:bg-foreground/90"><Play className="text-[var(--accent-atomic)]" fill="currentColor" /><span className="grid text-left text-[9px]">GET IT ON<strong className="text-sm">Google Play</strong></span></Button></div></div></div></SectionFrame>;
}
